load('nlfm2dopti.mat');
[fisl, fres,fmsl, fppr] = plotopti2d(a, kaiser_params, isls, ress,max_sidelobes, ppps);
filename = sprintf('../thesis/figures/%s-%ius-opti-isl.png', series_name,tau*1e6);
print(fisl, '-dpng', '-r300', filename);
filename = sprintf('../thesis/figures/%s-%ius-opti-res.png', series_name,tau*1e6);
print(fres, '-dpng', '-r300', filename);
filename = sprintf('../thesis/figures/%s-%ius-opti-msl.png', series_name,tau*1e6);
print(fmsl, '-dpng', '-r300', filename);
filename = sprintf('../thesis/figures/%s-%ius-opti-ppr.png', series_name,tau*1e6);
print(fppr, '-dpng', '-r300', filename);
